version: "3.7"
services:
  proyecto-monolitica:
    container_name : proyecto-monolitica
    image : proyecto-monolitica:v1
    build :
      context : .
    ports :  
      - "2000:2000"
    networks :
      - proyectos-app

networks :
  proyectos-app :